# -*- coding: utf-8 -*-
"""Assignment 5 .py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IlqSF82y054DMdr6ZZFHxE-mhrxyDzam
"""

def most_frequent(string):
  d=dict()
  for key in string:
    if key not in d:
      d[key]=1
  else:
        d[key] += 1
        return d
  print('Mississippi',most_frequent)