# -*- coding: utf-8 -*-
"""Assignment 1 .py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IlqSF82y054DMdr6ZZFHxE-mhrxyDzam
"""

r = float(input("enter the radius:"));
from math import pi;
area=r*r*pi;
print("area of circle =",area);